"use client";
import { ArrowLeft, FileCode2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { inputLabel, formatNumber as number } from "@/lib/dashboard-data";
import type { TraceDetail } from "@/lib/types";
export default function TracePanel({detail, onBack}: {detail: TraceDetail; onBack: () => void}) {
  const result = detail.result;
  const candidate = detail.candidate_tokens;
  return <section className="trace-panel">
    <Button variant="ghost" size="sm" onClick={onBack}><ArrowLeft data-icon="inline-start"/>Back to activity</Button>
    <div className="page-heading"><div><h1>Context trace</h1><p>{detail.client} · {new Date(detail.timestamp).toLocaleString()} · index revision {detail.revision}</p></div><Badge variant="secondary">{detail.operation}</Badge></div>
    <div className="request-block"><small>AGENT REQUEST</small><h2>{inputLabel(detail)}</h2><code>{detail.id}</code></div>
    <div className="trace-metrics"><div><small>Available context</small><strong>{number(candidate)}<span> tokens</span></strong></div><div><small>Returned context</small><strong>{number(detail.returned_tokens)}<span> tokens</span></strong></div><div><small>Caller budget</small><strong>{number(detail.token_budget)}<span> tokens</span></strong></div><div><small>Execution</small><strong>{detail.latency_ms}<span> ms</span></strong></div></div>
    <div className="context-scale"><div className="scale-label"><span>Returned from candidate context</span><span>{candidate ? Math.round(detail.returned_tokens / candidate * 100) : 0}% included · {detail.cache_hit ? "cache hit" : "cache miss"}</span></div><div className="large-meter"><span style={{width:`${candidate ? Math.min(100, detail.returned_tokens / candidate * 100) : 0}%`}}/></div><p>Context is selected to fit the task and caller’s budget. Smaller is not inherently better.</p></div>
    {result?.error && <p className="error">{result.error}</p>}
    <div className="trace-columns"><section><h2>Execution path</h2><ol className="steps">{result?.steps?.map((step, i) => <li key={i}><span>{String(i+1).padStart(2,"0")}</span><div><strong>{step.name}</strong><small>{step.files !== undefined ? `${step.files} files` : step.relationships !== undefined ? `${step.relationships} relationships` : `${step.returned_tokens} tokens`}</small></div></li>)}</ol></section><section><h2>Selected sources <span className="count">{result?.included_files?.length || 0}</span></h2><ul className="sources">{result?.sources?.map(source => <li key={source.path}><FileCode2 size={15}/><div><code>{source.path}</code><small>{source.reason}{source.parse_errors ? " · parse errors present" : ""}</small></div><span>{number(source.tokens)} tokens</span></li>)}</ul>{!!result?.truncated_files?.length && <p className="hint">Truncated: {result.truncated_files.join(", ")}</p>}<details><summary>Omitted files ({result?.omitted_files?.length || 0})</summary><ul className="omitted">{result?.omitted_files?.map(p => <li key={p}><code>{p}</code></li>)}</ul></details><details><summary>Files considered ({result?.files_considered?.length || 0})</summary><ul className="omitted">{result?.files_considered?.map(p => <li key={p}><code>{p}</code></li>)}</ul></details></section></div>
    <section className="relationships"><h2>Relationships traversed</h2>{result?.relationships?.length ? <div className="table-scroll"><table><thead><tr><th>Source</th><th>Relationship</th><th>Target</th></tr></thead><tbody>{result.relationships.map((r,i) => <tr key={i}><td><code>{r.source}</code></td><td>{r.kind}{r.heuristic && <small> · heuristic</small>}</td><td><code>{r.target}</code></td></tr>)}</tbody></table></div> : <p className="hint">No relationships traversed for this operation.</p>}</section>
    {!!result?.selection?.length && <details className="relationships"><summary>Context selection evidence ({result.selection.length} candidates)</summary><div className="table-scroll"><table><thead><tr><th>Path</th><th>Status</th><th>Score / distance</th><th>New tokens</th><th>Reason / relationship</th></tr></thead><tbody>{result.selection.map(row=><tr key={row.path}><td><code>{row.path}</code></td><td>{row.status}</td><td>{row.score ?? row.priority}<small> · {row.graph_distance ?? "—"} hops{row.already_known ? " · already supplied" : ""}</small></td><td>{number(row.token_cost)}</td><td>{row.reason}{row.score_reasons?.map((reason,i)=><small key={i}> · {reason.signal} {reason.weight >= 0 ? "+" : ""}{reason.weight}</small>)}{row.relationship && <small> · {row.relationship.kind}: {row.relationship.source} → {row.relationship.target}</small>}{row.omission_reason && <small> · {row.omission_reason}</small>}</td></tr>)}</tbody></table></div><p className="hint">Configurable structural scores and marginal token cost guide selection. Reasons show additive weights; block costs include file headers. Separators also count toward the compiled context budget.</p></details>}
    {result?.metrics && <details className="relationships"><summary>Context delta and runtime timing</summary><pre>{JSON.stringify({delta:result.metrics, timings_ms:result.timings_ms, previous_context:result.previous_context},null,2)}</pre><p className="hint">Previously supplied context is referenced when unchanged. Framing and token boundaries can prevent exact addition of delta totals. Smaller context is not inherently better.</p></details>}
    {(result?.manifest || result?.pattern_evidence?.length || result?.invalidations?.length) && <details className="relationships"><summary>Context manifest, invalidation and interaction patterns</summary><pre>{JSON.stringify({context_id:result.context_id, manifest:result.manifest, structural_selection:result.structural_selection, invalidations:result.invalidations, patterns:result.pattern_evidence, overhead:result.overhead},null,2)}</pre></details>}
    <section className="compiled"><div className="section-heading"><h2>Compiled context</h2><small>{number(detail.returned_tokens)} tokens</small></div><pre>{result?.context || "No context matched this request within the budget."}</pre><p className="hint">{result?.budget_scope}</p></section>
    <details className="raw-input"><summary>Request parameters and trace metadata</summary><pre>{JSON.stringify({inputs: detail.inputs, session: detail.session_id, otel_trace_id: detail.otel_trace_id, index: result?.index}, null, 2)}</pre></details>
  </section>;
}
